name: Run versioning Script

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Run python script
        run: |
          python backend/version.py

      - name: Configure Git
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"

      - name: Commit current_version.txt
        run: |
          git add current_version.txt
          git commit -m "Update version number [skip ci]" || echo "No changes to commit"

      - name: Push changes
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin master